### ISSUE TITLE
Important Inquiry Regarding This Package

### ISSUE THREAD

**Issue by BobDotCom** [alesanfra/pycord#2]
Hey @alesanfra,

I have a question regarding the name of this package on PyPi. Please contact me as soon as possible. You can reach me at
- Email: `bobdotcomgt@gmail.com`
- Discord: `BobDotCom#4428`

Thanks for your time,
    BobDotCom

**Comment by alesanfra** [comment]
Hi @BobDotCom, feel free to ask anything here, I'll try to answer 😄

**Comment by BobDotCom** [comment]
Hey @alesanfra, 

I own a project under the same name as this one, a python API wrapper for discord. I wanted to see if you were still maintaining this project, and if not, would you consider transferring the project name on PyPi to us? Our project can be found [here](https://github.com/Pycord-Development/pycord). Let me know if you have any other questions regarding this.

Thanks,
    BobDotCom

**Comment by BobDotCom** [comment]
Hey @alesanfra,

Just checking in to see if you had made a decision yet. If you have any questions I'd be happy to answer them either here or on any of the private contact methods I provided in my first post.

As an addition, if you would like to keep this project active on PyPi we would be willing to transfer our current package name, `py-cord` to you in exchange for `pycord` if that helps. I hope we can reach an agreement and look forward to your response.

Thanks,
BobDotCom

**Comment by alesanfra** [comment]
Hi @BobDotCom, I understand the motivations behind your request but the name of this project isn't really for sale. Moreover any change to the name would break all projects which relies on it. 
This project is still active, and since it's just a tiny wrapper on top of ffmpeg it doesn't require active maintenance unless a breaking change is introduced in ffmpeg (which happens rarely, by the way).

Hope this answer the inquiry, 

AS

**Comment by CodeWithSwastik** [comment]
Hi @alesanfra, 

The changes to name in PyPi would not affect the changes in the import name. So projects using your package wouldn't need to change imports. 

You may have already seen the incorrectly marked [Used By](https://user-images.githubusercontent.com/61446939/132462681-910a72d7-a3ac-477d-af26-efa05db9fd5e.png) in your repo. This will only increase as more and more people try to install our package but it would install your package which would not be good for either of us.

Thanks, 
Swas

**Comment by alesanfra** [comment]
The change would break the requirements listed in any setup.py/requirements.txt/pyproject.toml, so as I said before I won't transfer the name. Pypi is full of packages with names which don't match their import name, it's not a big deal.

Bests,
AS

**Comment by RPSMain** [comment]
F
